version: '3.9'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: ${SA_PASSWORD}
    ports:
      - '${SQL_SERVER_PORT}:1433'
    volumes:
      - ./DATABASE:/var/opt/mssql/data
  frontend:
    build:
      context: FRONT
      dockerfile: Dockerfile
    ports:
      - '3000:80'
    depends_on:
      - sqlserver